version: '2'
services:
    blog:
        container_name: web-layer
        build:
            context: web-layer
        image: blog-service:latest
        ports:
            - 8080:8080
    db:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: 'db'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'password'
            MYSQL_ROOT_PASSWORD: 'password'
        ports:
            - '3307:3306'

